export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_USER_ACCOUNTS = 'FETCH_USER_ACCOUNTS';
export const SELECT_USER_ACCOUNT = 'SELECT_USER_ACCOUNT';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const SET_ACCOUNT_LOGO = 'SET_ACCOUNT_LOGO';

export const FETCH_USERS = 'FETCH_USERS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const SET_USER_ACCOUNTS = 'SET_USER_ACCOUNTS';
export const CLEAR_USER_ACCOUNTS = 'CLEAR_USER_ACCOUNTS';

export const VALIDATE_USER = 'VALIDATE_USER';
export const CREATE_ACCOUNT_CAMPAIGN = 'CREATE_ACCOUNT_CAMPAIGN';
export const FETCH_ACCOUNT_CAMPAIGNS = 'FETCH_ACCOUNT_CAMPAIGNS';
export const FETCH_SPECS = 'FETCH_SPECS';
export const SELECT_SPEC = 'SELECT_SPEC';
export const DESELECT_SPEC = 'DESELECT_SPEC';
export const SET_SPECS_SELECTED = 'SET_SPECS_SELECTED';
export const REMOVE_SPEC = 'REMOVE_SPEC';
export const ADD_SPEC = 'ADD_SPEC';
export const VIEW_SPEC = 'VIEW_SPEC';

export const CLEAR_SPEC = 'CLEAR_SPEC';
export const SET_SPEC_CAMPAIGN = 'SET_SPEC_CAMPAIGN';
export const SET_SPEC_MEDIUM = 'SET_SPEC_MEDIUM';
export const SET_SPEC_AD_FORMAT = 'SET_SPEC_AD_FORMAT';
export const SET_SPEC_CREATIVE = 'SET_SPEC_CREATIVE';
export const SET_SPEC_CONTENT = 'SET_SPEC_CONTENT';
export const SET_SPEC_CONTENT_FORMAT = 'SET_SPEC_CONTENT_FORMAT';

export const CLEAR_NEW_SPEC = 'CLEAR_NEW_SPEC';
export const SET_NEW_SPEC_MEDIUM = 'SET_NEW_SPEC_MEDIUM';
export const SET_NEW_SPEC_AD_FORMAT = 'SET_NEW_SPEC_AD_FORMAT';
export const SET_NEW_SPEC_CREATIVE = 'SET_NEW_SPEC_CREATIVE';
export const SET_NEW_SPEC_CREATIVE_DETAIL = 'SET_NEW_SPEC_CREATIVE_DETAIL';
export const SET_NEW_SPEC_CREATIVE_IMAGE = 'SET_NEW_SPEC_CREATIVE_IMAGE';
export const SET_NEW_SPEC_CONTENT_TYPE_TMP = 'SET_NEW_SPEC_CONTENT_TYPE_TMP';
export const SET_NEW_SPEC_CONTENT_FORMAT_TMP = 'SET_NEW_SPEC_CONTENT_FORMAT_TMP';
export const SET_NEW_SPEC_CONTENT_DETAIL_TMP = 'SET_NEW_SPEC_CONTENT_DETAIL_TMP';
export const SET_NEW_SPEC_CONTENT = 'SET_NEW_SPEC_CONTENT';
export const SET_NEW_SPEC_CONTENT_VIEW = 'SET_NEW_SPEC_CONTENT_VIEW';
export const CREATE_SPEC = 'CREATE_SPEC';
export const CREATE_CAMPAIGN_SPEC = 'CREATE_CAMPAIGN_SPEC';

export const FETCH_MEDIUMS = 'FETCH_MEDIUMS';
export const FETCH_AD_FORMATS = 'FETCH_AD_FORMATS';
export const FETCH_CREATIVES = 'FETCH_CREATIVES';
export const FETCH_CONTENT_TYPES = 'FETCH_CONTENT_TYPES';
export const FETCH_CONTENT_FORMATS = 'FETCH_CONTENT_FORMATS';

export const CLEAR_MEDIUMS = 'CLEAR_MEDIUMS';
export const CLEAR_AD_FORMATS = 'CLEAR_AD_FORMATS';
export const CLEAR_CREATIVES = 'CLEAR_CREATIVES';
export const CLEAR_CONTENT_TYPES = 'CLEAR_CONTENT_TYPES';
export const CLEAR_CONTENT_FORMATS = 'CLEAR_CONTENT_FORMATS';

export const FETCH_CONTENTS = 'FETCH_CONTENTS';
